const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",

    GET_POSTS: "GET_POSTS",
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
};

export default actionTypes;
