const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",

    GET_POSTS: "GET_POSTS",
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_PRICES: "GET_PRICES",
    GET_AREAS: "GET_AREAS",
    GET_PROVINCES: "GET_PROVINCES",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_LIMIT_ADMIN: "GET_POSTS_LIMIT_ADMIN",
    GET_POSTS_LIMIT_DATE: "GET_POSTS_LIMIT_DATE",

    // USER CURRENT
    GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
