export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Nav } from "./Nav";
export { default as Button } from "./Button";
export { default as InputForm } from "./InputForm";
export { default as Search } from "./Search";
export { default as Province } from "./Province";
export { default as Left } from "./Left";
export { default as Right } from "./Right";
