import {
    faUserPlus,
    faPlusCircle,
    faSignIn,
    faStar,
    faSms,
    faPhoneAlt,
    faEnvelope,
    faHouseUser,
    faSignOut,
    faChevronRight,
    faHotel,
    faMapMarkedAlt,
    faTag,
    faVectorSquare,
    faSearch,
    faHeart,
    faAngleDoubleRight,
    faAngleDoubleLeft,
} from "@fortawesome/free-solid-svg-icons";
// import { faHeart } from "@fortawesome/free-regular-svg-icons";

export const icons = {
    faHeart,
    faUserPlus,
    faPlusCircle,
    faSignIn,
    faStar,
    faSms,
    faPhoneAlt,
    faEnvelope,
    faHouseUser,
    faSignOut,
    faChevronRight,
    faHotel,
    faMapMarkedAlt,
    faTag,
    faVectorSquare,
    faSearch,
    faAngleDoubleRight,
    faAngleDoubleLeft,
};
